### ISSUE TITLE
Rename Crypto Monad

### ISSUE THREAD

**Issue by fabian-hk** [REPROSEC/dolev-yao-star-extrinsic#2]
I think the name ``crypto`` for the monad managing computations on the trace is misleading. That's why I want to propose some alternative names:

- mtrace (for monad trace)
- comp (for computation)
- hist (for protocol history)

Feel free to propose other alternatives. I personally think ``mtrace`` would make the most sense.

**Comment by qaphla** [comment]
I have no strong opinions, other than to not use `crypto`. Of the suggestions so far, I like `mtrace` and `traceful` the best. `trace` is most natural to me from a functional background, analogous to `state`, but then this causes conflict with the type `trace`.

**Comment by TWal** [comment]
Closed by #31.
