### ISSUE TITLE
Rework the trace API

### ISSUE THREAD

**Issue by TWal** [REPROSEC/dolev-yao-star-extrinsic#61]
As noted by the comments in #55, there is some friction associated with the trace API.

Here is a list.

The `length` function on `trace`s is shadowed by the `length` function on `bytes`, so that we need to namespace it, either by doing `DY.Core.Trace.Type.length` or by doing `module T = DY.Core.Trace.Type` … `T.length`. We could rename it to `trace_length` to simplify things.
https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/9c8d4d8d300755ea6d338c8afd147ff27ba1fa24/src/lib/utils/DY.Lib.Printing.fst#L250

The DY* user never has to use `Snoc` because the trace API takes care of that. However the DY* user has to use `Nil` because there is no `empty_trace` function.
https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/9c8d4d8d300755ea6d338c8afd147ff27ba1fa24/examples/iso_dh/DY.Example.DH.Debug.fst#L66

In NSL but also in the lemmas about `mk_rand`, we use a property on traces that the last event is some `RandGen` event. We could factorize this in a trace predicate.
https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/9c8d4d8d300755ea6d338c8afd147ff27ba1fa24/src/core/DY.Core.Trace.Manipulation.fst#L257-L258

**Comment by TWal** [comment]
Proposed actions:

Rename `DY.Core.Trace.Type.length` to `trace_length`.

Add `val empty_trace: trace`

Add `val rand_just_generated: trace -> bytes -> prop`

**Comment by cwaldm** [comment]
I'll probably work on these points soon (unless someone else already did?), since I want the `list_to_trace` for the tutorial.
Are there any other things that came up in the meantime that I can deal with while doing that?
