### ISSUE TITLE
Type alias for traceful + option

### ISSUE THREAD

**Issue by cwaldm** [REPROSEC/dolev-yao-star-extrinsic#69]
I'm annoyed by having to write parentheses when using the combined `traceful (option a)` monad.
I suggest to introduce a type alias for this.
For example 
```fstar 
type trace_option a = traceful (option a)
```

I'm starting this discussion to see:
1. Whether you think it makes sense or it's not worth the effort ?
2. What the name should be? (Wich combination of `traceful`, `trace`, `tr` and `option` or `opt`?) Following other naming conventions it should probably be `traceful_option` but `trace_option` could also be fine.

Once we agree to have this and decided on a name, I can do the changes and adapt all files to use the new alias.

**Comment by TWal** [comment]
Couldn't this also be worked-around with a snippet mechanism in the editor? This would avoid introducing a new type alias while still being comfortable to type.

**Comment by cwaldm** [comment]
Why do you want to avoid a new type alias?

**Comment by AlexHodder** [comment]
I personally prefer the original `traceful (option x)` for both readability and typing, but it's very minor for me.

**Comment by cwaldm** [comment]
Of course, it's a minor thing!

I agree, that a type alias is another thing, a user has to look at the first time. But I think, if we have a good name, it's a non-issue for newcomers. (Especially compared to other things (types, classes, concepts) we have in DY* that are not at all easily understandable....)

Since we are talking about editors: if we use `_`, the completion in my editor finds the whole term. So it's not just about typing `_` vs `()` for me.

But of course, if the majority wants to leave it as is, that's fine.

**Comment by cwaldm** [comment]
Closing, as no one really seems to support this.
