### ISSUE TITLE
The distinction between trace event and protocol event can be confusing for newcomers

### ISSUE THREAD

**Issue by TWal** [REPROSEC/dolev-yao-star-extrinsic#74]
Mentioned by @qaphla in https://github.com/REPROSEC/dolev-yao-star-extrinsic/pull/73#pullrequestreview-2366926909

**Comment by cwaldm** [comment]
How about renaming the trace events to "trace_entry"?
Then we have the intuitive 
* `trace = rev_list trace_entry`
* `get_entry_at` (instead of `get_event_at`)
* `entry_exists`
...

**Comment by TWal** [comment]
I think that would be fine!
