### ISSUE TITLE
Should `LongTermPkEncKey` be renamed to `LongTermPkDecKey` ?

### ISSUE THREAD

**Issue by cwaldm** [REPROSEC/dolev-yao-star-extrinsic#85]
Shouldn't this
https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/20d5ae49ae3560dbfadbfa3484db21ab14ac2496/src/lib/state/DY.Lib.State.PrivateKeys.fst#L21
rather be called `Dec` key ?

In particular, looking at
https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/20d5ae49ae3560dbfadbfa3484db21ab14ac2496/src/lib/state/DY.Lib.State.PrivateKeys.fst#L73-L77
shows that we are here talking about a *DE*cryption key (and not an encryption key as the name suggests).
Or am I missing something?

**Comment by TWal** [comment]
There is also https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/20d5ae49ae3560dbfadbfa3484db21ab14ac2496/src/lib/state/DY.Lib.State.PrivateKeys.fst#L85-L89
in which it makes sense, so changing to `Dec` would not make sense as a public key.

This is the result of #65 that merged `public_key_type` and `private_key_type` into this `long_term_key_type`.

**Comment by cwaldm** [comment]
I see. I still think, the name is confusing if it refers to both encryption and decryption keys.
Would it make sense to rename it to just `LongTermPkKey` ?

Looking at https://github.com/REPROSEC/dolev-yao-star-extrinsic/blob/20d5ae49ae3560dbfadbfa3484db21ab14ac2496/src/lib/state/DY.Lib.State.PrivateKeys.fst#L66-L68 this would match the `SigKey` case.

**Comment by TWal** [comment]
Why not, but I fear it would be confusing in another way because the term "public key" is heavily overloaded: it may mean a public key for signature, for asymmetric encryption, for KEM, etc.
The names "asymmetric encryption" / "symmetric encryption" are also called "public-key encryption" and "secret-key encryption", so I guess this can explain using "PkEnc" here.

**Comment by TWal** [comment]
What about using `PKE` for Public-Key Encryption? It seems to be somewhat standard, and we are already using acronyms (AEAD, KDF, etc)

**Comment by cwaldm** [comment]
Ok. `LongTermPKEKey` could be fine.
But then, I would also rename `PkKey` and `PkNonce` to `PKEKey` and `PKENonce`.
(Althoug, to be consistent with the other usage constructors, it should probably be `PkeKey` ?)

**Comment by TWal** [comment]
Yes, that would make sense! Indeed I went for `AeadKey` rather than `AEADKey`, I think the rationale was that I find it easier to see where words should be cut in the first case than in the second, but that's something personal.

**Comment by TWal** [comment]
Fixed by #91
